---
repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.22.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional", "@commitlint/cli"]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0  # or specific git tag
  hooks:
    - id: bundler-audit
    - id: check-mailmap
- repo: https://github.com/klieret/jekyll-relative-url-check
  rev: v2.0.2
  hooks:
    - id: jekyll-relative-url-check-html
    - id: jekyll-relative-url-check-markdown
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.12.0
  hooks:
    - id: markdownlint
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_schedule: weekly
  skip:
    - bundler-audit
