---
repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional"]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6  # or specific git tag
  hooks:
    - id: bundler-audit
    - id: markdownlint # Configure in .mdlrc
