---
repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional"]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6  # or specific git tag
  hooks:
    - id: bundler-audit
    - id: check-mailmap
    - id: git-dirty  # Configure in .gitignore
    - id: markdownlint # Configure in .mdlrc
    - id: bundler-audit
    - id: forbid-binary
- repo: https://github.com/klieret/jekyll-relative-url-check
  rev: v2.0.1
  hooks:
    - id: jekyll-relative-url-check-html
    - id: jekyll-relative-url-check-markdown
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_schedule: weekly
  skip: []