---
repos:
# - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
#   rev: v2.2.0
#   hooks:
#       - id: commitlint
#         stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: master  # or specific git tag
  hooks:
    - id: bundler-audit
    - id: check-mailmap
    - id: fasterer
    - id: forbid-binary
    - id: git-check  # Configure in .gitattributes
    - id: git-dirty  # Configure in .gitignore
    - id: markdownlint # Configure in .mdlrc
    - id: reek
    - id: require-ascii
    - id: rubocop
    - id: script-must-have-extension
    - id: shellcheck
    - id: shfmt
