# Site settings
title: Upgraded Adventure
description: 'Upgraded Adventures of Bruce Becker'
url: 'https://www.brucellino.dev'
baseurl: ''
author:
  name: 'Bruce Becker'
  email: brucellino@hey.com
  twitter_username: brusisceddu
  github_username:  brucellino
  linkedin_username:  brucebecker

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate', 'jekyll-toc']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
